export enum COLOR {
  BLUE_VIOLET = "blueviolet",
  DODGER_BLUE = "dodgerblue",
  DARK_BLUE = "darkblue",
  BLACK = "black",
  FOREST_GREEN = "forestgreen",
  GOLDEN_ROD = "goldenrod",
  LIGHT_SALMON = "lightsalmon",
  ORANGE_RED = "orangered",
  CYAN = "cyan",
  BLUE = "blue",
  GEEK_BLUE = "geekblue",
  DIM_GREY = "dimgrey",
  DEEP_SKY_BLUE = "deepskyblue",
  VOLCANO = "volcano",
  DARK_GOLDEN_ROD = "darkgoldenrod",
  NONE = "white",
}
