import { Dish } from "@typings/Dish.ts";

export enum UNLOCK_TYPE {
  YOSHIE_VISIT = "요시에 방문",
  ENTER_HYDROTHERMAL_VENTS = "열수 분출 구역 진입",
  RESCUE_TSHCHI = "츠치 구조",
  VIP_VINCENT = "빈센트 접대 성공",
  VIP_MICHAEL_BANG = "마이클 방 접대 성공",
  VIP_SAMMY = "새미 접대 성공",
  DJANGO_VISIT = "방랑 상인 장고 방문",
  VIP_DJANGO = "방랑 상인 장고 접대 성공",
  CHALLENGE_WANG_PANG = "왕팡 대결 승리",
  CHALLENGE_ALEX = "알렉스 대결 승리",
  CHALLENGE_PASTRO = "파스트로 대결 승리",
  COOK_STAR_BRONZE = "쿡스타 브론즈 달성",
  COOK_STAR_SILVER = "쿡스타 실버 달성",
  COOK_STAR_GOLD = "쿡스타 골드 달성",
  COOK_STAR_PLATINUM = "쿡스타 플래티넘 달성",
  COOK_STAR_DIA = "쿡스타 다이아몬드 달성",
  PARTY_TUNA = "참치 요트 파티 시작",
  PARTY_BLUE_FIN = "청새치 파티 시작",
  PARTY_CUCUMBER = "오이 파티 시작",
  PARTY_LOBSTER = "랍스터 파티 시작",
  SECRET_RECIPE = "비밀 레시피",
}

export enum PARTY {
  TUNA = "참치 요트 파티",
  BLUE_FIN = "청새치 파티",
  CUCUMBER = "오이 파티",
  CURRY = "카레 파티",
}

export enum RECIPE_TYPE {
  FISH = "FISH",
  INGREDIENT = "INGREDIENT",
  SEASONING = "SEASONING",
}

export const DISH_LIST: Dish[] = [
  // 기본 초밥
  {
    id: "Clownfish_Sushi",
    name: "흰동가리 초밥",
    maxCost: 7,
    maxScore: 120,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰동가리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Comber_Sushi",
    name: "콤버 초밥",
    maxCost: 7,
    maxScore: 140,
    maxCount: 1,
    recipeList: [{ id: "", name: "콤버", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Cardinal_Fish_Sushi",
    name: "지중해카디널피쉬 초밥",
    maxCost: 11,
    maxScore: 100,
    maxCount: 1,
    recipeList: [
      { id: "", name: "지중해카디널피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sea_Goldie_Sushi",
    name: "금강바리",
    maxCost: 11,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "금강바리 초밥", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pyramid_Butterflyfish_Sushi",
    name: "안개나비고기 초밥",
    maxCost: 14,
    maxScore: 100,
    maxCount: 1,
    recipeList: [
      { id: "", name: "안개나비고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellow_Tang_Sushi",
    name: "옐로우탱 초밥",
    maxCost: 14,
    maxScore: 100,
    maxCount: 1,
    recipeList: [
      { id: "", name: "옐로우탱", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blackspot_Seabream_Sushi",
    name: "사르파살파 초밥",
    maxCost: 18,
    maxScore: 110,
    maxCount: 1,
    recipeList: [
      { id: "", name: "사르파살파", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Orbicular_Batfish_Fry",
    name: "원반제비활치 튀김",
    maxCost: 18,
    maxScore: 110,
    maxCount: 1,
    recipeList: [
      { id: "", name: "원반제비활치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blue_Tang_Sushi",
    name: "블루탱 초밥",
    maxCost: 22,
    maxScore: 110,
    maxCount: 1,
    recipeList: [{ id: "", name: "블루탱", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Rainbow_Wrasse_Sushi",
    name: "무지개놀래기 초밥",
    maxCost: 22,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무지개놀래기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Lagoon_Triggerfish_Sushi",
    name: "배주름쥐치 초밥",
    maxCost: 22,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "배주름쥐치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Small_Spotted_Dart_Sushi",
    name: "빨판매가리 초밥",
    maxCost: 29,
    maxScore: 120,
    maxCount: 1,
    recipeList: [
      { id: "", name: "빨판매가리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowback_Fusilier_Sushi",
    name: "황등어 초밥",
    maxCost: 25,
    maxScore: 120,
    maxCount: 1,
    recipeList: [{ id: "", name: "황등어", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Ornate_Wrasse_Sushi",
    name: "오네이트놀래기 초밥",
    maxCost: 29,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "오네이트놀래기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Longfin_Batfish_Sushi",
    name: "깃털제비활치 초밥",
    maxCost: 37,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "깃털제비활치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Mediterranean_Parrotfish_Sushi",
    name: "지중해비늘돔 초밥",
    maxCost: 37,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "지중해비늘돔", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Redtooth_Triggerfish_Sushi",
    name: "붉은이빨쥐치 초밥",
    maxCost: 33,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "붉은이빨쥐치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Black_And_White_Snapper_Sushi",
    name: "블랙스내퍼 초밥",
    maxCost: 33,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블랙스내퍼", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Green_Humphead_Parrotfish_Sushi",
    name: "버팔로피쉬 초밥",
    maxCost: 59,
    maxScore: 230,
    maxCount: 1,
    recipeList: [
      { id: "", name: "버팔로피쉬 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Barrel_Jellyfish_Sushi",
    name: "배럴해파리 군함 초밥",
    maxCost: 37,
    maxScore: 160,
    maxCount: 1,
    recipeList: [
      { id: "", name: "배럴해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Fried_Egg_Jellyfish_Sushi",
    name: "달걀프라이해파리 군함 초밥",
    maxCost: 29,
    maxScore: 160,
    maxCount: 1,
    recipeList: [
      { id: "", name: "달걀프라이해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Whitetip_Reefshark_Sushi",
    name: "백기흉상어 초밥",
    maxCost: 88,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "백기흉상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Moray_Eel_Sushi",
    name: "곰치 초밥",
    maxCost: 185,
    maxScore: 250,
    maxCount: 1,
    recipeList: [{ id: "", name: "곰치", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Red_Lionfish_Sushi",
    name: "쏠배감펭 초밥",
    maxCost: 37,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "쏠배감펭", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Titan_Triggerfish_Sushi",
    name: "타이탄트리거피쉬 초밥",
    maxCost: 55,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "타이탄트리거피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blacktip_Reefshark_Sushi",
    name: "흑기흉상어 초밥",
    maxCost: 222,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흑기흉상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Copper_Shark_Sushi",
    name: "무태상어 초밥",
    maxCost: 240,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무태상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Box_Jellyfish_Sushi",
    name: "상자해파리 군함 초밥",
    maxCost: 203,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "상자해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluefin_Tuna_Akami_Sushi",
    name: "참다랑어 붉은살 초밥",
    maxCost: 296,
    maxScore: 240,
    maxCount: 1,
    recipeList: [
      { id: "", name: "참다랑어 붉은살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluefin_Tuna_Chutoro_Sushi",
    name: "참다랑어 중뱃살 초밥",
    maxCost: 351,
    maxScore: 241,
    maxCount: 1,
    recipeList: [
      { id: "", name: "참다랑어 중뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluefin_Tuna_Otoro_Sushi",
    name: "참다랑어 대뱃살 초밥",
    maxCost: 499,
    maxScore: 330,
    maxCount: 1,
    recipeList: [
      { id: "", name: "참다랑어 대뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowfin_Tuna_Akami_Sushi",
    name: "황다랑어 붉은살 초밥",
    maxCost: 270,
    maxScore: 235,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황다랑어 붉은살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowfin_Tuna_Chutoro_Sushi",
    name: "황다랑어 중뱃살 초밥",
    maxCost: 333,
    maxScore: 238,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황다랑어 중뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowfin_Tuna_Otoro_Sushi",
    name: "황다랑어 대뱃살 초밥",
    maxCost: 462,
    maxScore: 315,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황다랑어 대뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Flame_Angelfish_Sushi",
    name: "라마엔젤피쉬 초밥",
    maxCost: 18,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "라마엔젤피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sheepshead_Sushi",
    name: "혹돔 초밥",
    maxCost: 55,
    maxScore: 240,
    maxCount: 1,
    recipeList: [{ id: "", name: "혹돔", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Emperor_Angelfish_Sushi",
    name: "황제엔젤피쉬 초밥",
    maxCost: 37,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황제엔젤피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Stingray_Sushi",
    name: "노랑가오리 초밥",
    maxCost: 92,
    maxScore: 260,
    maxCount: 1,
    recipeList: [
      { id: "", name: "노랑가오리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Marbled_Electric_Ray_Sushi",
    name: "마블전기가오리 초밥",
    maxCost: 333,
    maxScore: 300,
    maxCount: 1,
    recipeList: [
      { id: "", name: "마블전기가오리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Cooked_Whiteleg_Shrimp_Sushi",
    name: "흰다리자숙새우 초밥",
    maxCost: 129,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰다리자숙새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Striped_Catfish_Sushi",
    name: "쏠종개 초밥",
    maxCost: 18,
    maxScore: 260,
    maxCount: 1,
    recipeList: [{ id: "", name: "쏠종개", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Purple_Sea_Urchin_Sushi",
    name: "보라성게 초밥",
    maxCost: 222,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "보라성게 초밥", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Shortfin_Mako_Sushi",
    name: "청상아리 초밥",
    maxCost: 388,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "청상아리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Zebra_Shark_Sushi",
    name: "지브라상어 초밥",
    maxCost: 399,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "지브라상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Marlin_Sushi",
    name: "청새치 초밥",
    maxCost: 341,
    maxScore: 370,
    maxCount: 1,
    recipeList: [
      { id: "", name: "청새치 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Thresher_Shark_Sushi",
    name: "환도상어 초밥",
    maxCost: 588,
    maxScore: 390,
    maxCount: 1,
    recipeList: [
      { id: "", name: "환도상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "American_Lobster_Sushi",
    name: "미국바닷가재 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "미국바닷가재", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "European_Lobster_Sushi",
    name: "유렵바닷가재 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "유렵바닷가재", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluehead_Tilefish_Sushi",
    name: "블루헤드타일피쉬 초밥",
    maxCost: 55,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블루헤드타일피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Clown_Frogfish_Sushi",
    name: "무당씬벵이 초밥",
    maxCost: 55,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무당씬벵이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Painted_Comber_Sushi",
    name: "페인티드콤버 초밥",
    maxCost: 32,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "페인티드콤버", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bigeye_Scad_Sushi",
    name: "새가라지 초밥",
    maxCost: 62,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "새가라지", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Striped_Red_Mullet_Sushi",
    name: "노랑촉수 초밥",
    maxCost: 59,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "노랑촉수", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Mackerel_Scad_Sushi",
    name: "풀가라지 초밥",
    maxCost: 55,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "풀가라지", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Harleqiun_Hind_Sushi",
    name: "청줄바리 초밥",
    maxCost: 66,
    maxScore: 180,
    maxCount: 1,
    recipeList: [
      { id: "", name: "청줄바리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bigeye_Trevally_Sushi",
    name: "줄전갱이 초밥",
    maxCost: 70,
    maxScore: 170,
    maxCount: 1,
    recipeList: [
      { id: "", name: "줄전갱이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Coral_Trout_Sushi",
    name: "무늬바리 초밥",
    maxCost: 66,
    maxScore: 170,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무늬바리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Grey_Triggerfish_Sushi",
    name: "갈쥐치 초밥",
    maxCost: 62,
    maxScore: 170,
    maxCount: 1,
    recipeList: [{ id: "", name: "갈쥐치", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Atlantic_Bonito_Sushi",
    name: "대서양보니토 초밥",
    maxCost: 77,
    maxScore: 180,
    maxCount: 1,
    recipeList: [
      { id: "", name: "대서양보니토", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "White_Trevally_Sushi",
    name: "흑점줄전갱이 초밥",
    maxCost: 81,
    maxScore: 190,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흑점줄전갱이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Cuttlefish_Sushi",
    name: "갑오징어 초밥",
    maxCost: 74,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "갑오징어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Dusky_Grouper_Sushi",
    name: "머구리농어 초밥",
    maxCost: 81,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "머구리농어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Atlantic_Mackerel_Sushi",
    name: "대서양고등어 초밥",
    maxCost: 77,
    maxScore: 190,
    maxCount: 1,
    recipeList: [
      { id: "", name: "대서양고등어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Giant_Trevally_Sushi",
    name: "무명갈전갱이 초밥",
    maxCost: 111,
    maxScore: 250,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무명갈전갱이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Giant_Trevally_Sushi",
    name: "흰점박이해파리 군함 초밥",
    maxCost: 66,
    maxScore: 180,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰점박이해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Tiger_Shark_Sushi",
    name: "뱀상어 초밥",
    maxCost: 185,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "뱀상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Great_Barracuda_Sushi",
    name: "큰꼬치고기 초밥",
    maxCost: 74,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "큰꼬치고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Narrow_Barred_Spanish_Mackerel_Sushi",
    name: "동갈삼치 초밥",
    maxCost: 74,
    maxScore: 190,
    maxCount: 1,
    recipeList: [
      { id: "", name: "동갈삼치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Longnose_Sawshark_Sushi",
    name: "톱상어 초밥",
    maxCost: 129,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "톱상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Atlantic_Anglerfish_Sushi",
    name: "대서양아귀 초밥",
    maxCost: 76,
    maxScore: 240,
    maxCount: 1,
    recipeList: [
      { id: "", name: "대서양아귀", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sally_Lightfoot_Crab_Sushi",
    name: "갈라파고스붉은게살 초밥",
    maxCost: 185,
    maxScore: 320,
    maxCount: 1,
    recipeList: [
      { id: "", name: "갈라파고스붉은게", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Raw_Black_Tiger_Shrimp_Sushi",
    name: "블랙타이거생새우 초밥",
    maxCost: 185,
    maxScore: 240,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블랙타이거새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sailfish_Sushi",
    name: "돛새치 초밥",
    maxCost: 336,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "돛새치 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Smooth_Hammerhead_Sushi",
    name: "귀상어 초밥",
    maxCost: 521,
    maxScore: 390,
    maxCount: 1,
    recipeList: [
      { id: "", name: "귀상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "California_Spiny_Lobster_Sushi",
    name: "캘리포니아닭새우 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "캘리포니아닭새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Tropical_Rock_Lobster_Sushi",
    name: "비단닭새우 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "비단닭새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Clearfin_Lionfish_Sushi",
    name: "방사쏠배감펭 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "방사쏠배감펭", name: "", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Longspine_Squirrelfish_Sushi",
    name: "롱스파인 다람쥐고기 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "롱스파인 다람쥐고기", name: "", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "White_Shrimp_Sushi",
    name: "흰보리새우 초밥",
    maxCost: 196,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰보리새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Red_Banded_Lobster_Sushi",
    name: "가시발새우 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "가시발새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blue_Lobster_Sushi",
    name: "블루랍스터 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블루랍스터", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blackfin_Barracuda_Sushi",
    name: "검정핀꼬치고기 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "검정핀꼬치고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Spear_Squid_Sushi",
    name: "화살오징어 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "화살오징어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Humboldt_Squid_Sushi",
    name: "훔볼트오징어 초밥",
    maxCost: 536,
    maxScore: 350,
    maxCount: 1,
    recipeList: [
      { id: "", name: "훔볼트오징어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Devil_Scorpion_Fish_Sushi",
    name: "데빌스콜피온피쉬 초밥",
    maxCost: 499,
    maxScore: 350,
    maxCount: 1,
    recipeList: [
      { id: "", name: "데빌스콜피온피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Fan_Lobster_Sushi",
    name: "부채새우 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "부채새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Crystal_Lobster_Sushi",
    name: "크리스탈랍스터 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "크리스탈랍스터", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Chambered_Nautilus_Sushi",
    name: "앵무조개 초밥",
    maxCost: 129,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "앵무조개", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Fangtooth_Sushi",
    name: "귀신고기 초밥",
    maxCost: 166,
    maxScore: 260,
    maxCount: 1,
    recipeList: [
      { id: "", name: "귀신고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Frilled_Shark_Sushi",
    name: "주름상어 초밥",
    maxCost: 314,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "주름상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluespotted_Stargazer_Sushi",
    name: "푸렁통구멍 초밥",
    maxCost: 199,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "푸렁통구멍", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Rhinochimaeridae_Sushi",
    name: "코은상어 초밥",
    maxCost: 333,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "코은상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Spider_Crab_Sushi",
    name: "키다리게 초밥",
    maxCost: 185,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "키다리게", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Megamouth_Shark_Sushi",
    name: "메가마우스상어 초밥",
    maxCost: 351,
    maxScore: 300,
    maxCount: 1,
    recipeList: [
      { id: "", name: "메가마우스상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Cookiecutter_Shark_Sushi",
    name: "쿠키커터상어 초밥",
    maxCost: 277,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "쿠키커터상어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Clione_Sushi",
    name: "클리오네 초밥",
    maxCost: 129,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "클리오네", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sea_Toad_Sushi",
    name: "점씬벵이 초밥",
    maxCost: 203,
    maxScore: 230,
    maxCount: 1,
    recipeList: [
      { id: "", name: "점씬벵이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Salmon_Snailfish_Sushi",
    name: "분홍꼼치 초밥",
    maxCost: 222,
    maxScore: 230,
    maxCount: 1,
    recipeList: [
      { id: "", name: "분홍꼼치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pacific_Fanfish_Sushi",
    name: "벤텐어 초밥",
    maxCost: 240,
    maxScore: 240,
    maxCount: 1,
    recipeList: [{ id: "", name: "벤텐어", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Threetooth_Puffer_Sushi",
    name: "불뚝복 초밥",
    maxCost: 259,
    maxScore: 250,
    maxCount: 1,
    recipeList: [{ id: "", name: "불뚝복", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Comb_Jelly_Sushi",
    name: "감투빗해파리 초밥",
    maxCost: 166,
    maxScore: 250,
    maxCount: 1,
    recipeList: [
      { id: "", name: "감투빗해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blood-belly_Comb_Jelly_Sushi",
    name: "붉은배빗해파리 초밥",
    maxCost: 185,
    maxScore: 250,
    maxCount: 1,
    recipeList: [
      { id: "", name: "붉은배빗해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Red_Bream_Sushi",
    name: "금눈돔 초밥",
    maxCost: 129,
    maxScore: 270,
    maxCount: 1,
    recipeList: [{ id: "", name: "금눈돔", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Norway_Lobster_Sushi",
    name: "네점발빨간새우 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "네점발빨간새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Eastern_Rock_Lobster_Sushi",
    name: "동부바위바닷가재 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "동부바위바닷가재", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Peacock_Squid_Sushi",
    name: "공작오징어 초밥",
    maxCost: 277,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "공작오징어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Dumbo_Octopus_Sushi",
    name: "덤보문어 초밥",
    maxCost: 296,
    maxScore: 330,
    maxCount: 1,
    recipeList: [
      { id: "", name: "덤보문어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Barreleye_Sushi",
    name: "배럴아이 초밥",
    maxCost: 259,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "배럴아이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blob_Fish_Sushi",
    name: "블롭피쉬 초밥",
    maxCost: 444,
    maxScore: 310,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블롭피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Vampire_Squid_Sushi",
    name: "흡혈오징어",
    maxCost: 425,
    maxScore: 340,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흡혈오징어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pelican_Eel_Sushi",
    name: "펠리칸장어 초밥",
    maxCost: 666,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "펠리칸장어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Arctic_Cod_Sushi",
    name: "극지대구 초밥",
    maxCost: 351,
    maxScore: 340,
    maxCount: 1,
    recipeList: [
      { id: "", name: "극지대구", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Gelatinous_Snailfish_Sushi",
    name: "남극꼼치 초밥",
    maxCost: 314,
    maxScore: 330,
    maxCount: 1,
    recipeList: [
      { id: "", name: "남극꼼치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Antarctic_Octopus_Sushi",
    name: "남극문어 초밥",
    maxCost: 444,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "남극문어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Greenland_Shark_Sushi",
    name: "그린란드상어 초밥",
    maxCost: 592,
    maxScore: 370,
    maxCount: 1,
    recipeList: [
      { id: "", name: "그린란드상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Polar_Eelpout_Sushi",
    name: "북극등가시치 초밥",
    maxCost: 333,
    maxScore: 320,
    maxCount: 1,
    recipeList: [
      { id: "", name: "북극등가시치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Porbeagle_Shark_Sushi",
    name: "비악상어 초밥",
    maxCost: 610,
    maxScore: 380,
    maxCount: 1,
    recipeList: [
      { id: "", name: "비악상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Ice_Fish_Sushi",
    name: "아이스피쉬 초밥",
    maxCost: 351,
    maxScore: 320,
    maxCount: 1,
    recipeList: [
      { id: "", name: "아이스피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Capelin_Sushi",
    name: "열빙어 초밥",
    maxCost: 166,
    maxScore: 330,
    maxCount: 1,
    recipeList: [{ id: "", name: "열빙어", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Narwhal_Sushi",
    name: "일각고래 초밥",
    maxCost: 518,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "일각고래 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Haddock_Sushi",
    name: "해덕대구 초밥",
    maxCost: 407,
    maxScore: 340,
    maxCount: 1,
    recipeList: [
      { id: "", name: "해덕대구", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Starry_Skate_Sushi",
    name: "땅가오리 초밥",
    maxCost: 481,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "땅가오리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Arctic_Telescope_Fish_Sushi",
    name: "북극 망원경 물고기 초밥",
    maxCost: 444,
    maxScore: 350,
    maxCount: 1,
    recipeList: [
      { id: "", name: "북극 망원경 물고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Alaska_Pollock_Sushi",
    name: "알래스카 명태 초밥",
    maxCost: 499,
    maxScore: 380,
    maxCount: 1,
    recipeList: [
      { id: "", name: "알래스카 명태", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Lumpfish_Sushi",
    name: "럼프피쉬 초밥",
    maxCost: 444,
    maxScore: 370,
    maxCount: 1,
    recipeList: [
      { id: "", name: "럼프피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Snub_nosed_Spiny_Eel_Sushi",
    name: "들창코가시장어 초밥",
    maxCost: 666,
    maxScore: 390,
    maxCount: 1,
    recipeList: [
      { id: "", name: "들창코가시장어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Golden_King_Crab_Sushi",
    name: "황색왕게 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황색왕게", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Snow_Crab_Sushi",
    name: "대게 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [{ id: "", name: "대게", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Horsehair_Crab_Sushi",
    name: "털게 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [{ id: "", name: "털게", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Waptia_Sushi",
    name: "왑티아 초밥",
    maxCost: 381,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "왑티아 필덴시스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pikaia_Sushi",
    name: "피카이아 초밥",
    maxCost: 425,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "피카이아", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Allenypterus_Sushi",
    name: "알레니프테루스 초밥",
    maxCost: 462,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "알레니프테루스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Qingmendous_Sushi",
    name: "칭멘도스 초밥",
    maxCost: 444,
    maxScore: 310,
    maxCount: 1,
    recipeList: [
      { id: "", name: "칭멘도스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Falcatus_Sushi",
    name: "팔카투스 초밥",
    maxCost: 481,
    maxScore: 380,
    maxCount: 1,
    recipeList: [
      { id: "", name: "팔카투스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Drepanaspis_Sushi",
    name: "드레파나스피스 초밥",
    maxCost: 555,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "드레파나스피스 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Dunkleosteus_Sushi",
    name: "둔클레오스테우스 초밥",
    maxCost: 629,
    maxScore: 420,
    maxCount: 1,
    recipeList: [
      {
        id: "",
        name: "둔클레오스테우스 살점",
        type: RECIPE_TYPE.FISH,
        count: 1,
      },
    ],
  },
  {
    id: "Megalograptus_Sushi",
    name: "메갈로그랍투스 초밥",
    maxCost: 518,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "메갈로그랍투스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Xenacanthus_Sushi",
    name: "제나칸투스 초밥",
    maxCost: 592,
    maxScore: 430,
    maxCount: 1,
    recipeList: [
      { id: "", name: "제나칸투스 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Dollocaris_Ingens_Sushi",
    name: "돌로카리스인겐스 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "돌로카리스인겐스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Tokummia_Katalepsis_Sushi",
    name: "토큐미아카탈렙시스 초밥",
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [
      { id: "", name: "토큐미아카탈렙시스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Young_Anomalocaris_Sushi",
    name: "아노말로칼리스 새끼 초밥",
    maxCost: 224,
    maxScore: 125,
    maxCount: 1,
    recipeList: [
      { id: "", name: "아노말로칼리스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Seahorse_Sewers",
    name: "해마 꼬치구이",
    maxCost: 111,
    maxScore: 220,
    maxCount: 1,
    recipeList: [{ id: "", name: "해마", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Seadragon_Onigiri",
    name: "해룡 주먹밥",
    maxCost: 388,
    maxScore: 470,
    maxCount: 1,
    recipeList: [{ id: "", name: "해룡", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "",
    name: "",
    unlockType: UNLOCK_TYPE.YOSHIE_VISIT,
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [{ id: "", name: "", type: RECIPE_TYPE.FISH, count: 1 }],
  },
];
