import { Dish } from "@typings/Dish.ts";

export enum UNLOCK_TYPE {
  YOSHIE_VISIT = "요시에 방문",
  ENTER_HYDROTHERMAL_VENTS = "열수 분출 구역 진입",
  RESCUE_TSHCHI = "츠치 구조",
  VIP_VINCENT = "빈센트 접대 성공",
  VIP_MICHAEL_BANG = "마이클 방 접대 성공",
  VIP_SAMMY = "새미 접대 성공",
  DJANGO_VISIT = "방랑 상인 장고 방문",
  VIP_DJANGO = "방랑 상인 장고 접대 성공",
  CHALLENGE_WANG_PANG = "왕팡 대결 승리",
  CHALLENGE_ALEX = "알렉스 대결 승리",
  CHALLENGE_PASTRO = "파스트로 대결 승리",
  COOK_STAR_BRONZE = "쿡스타 브론즈 달성",
  COOK_STAR_SILVER = "쿡스타 실버 달성",
  COOK_STAR_GOLD = "쿡스타 골드 달성",
  COOK_STAR_PLATINUM = "쿡스타 플래티넘 달성",
  COOK_STAR_DIA = "쿡스타 다이아몬드 달성",
  PARTY_TUNA = "참치 요트 파티 시작",
  PARTY_BLUE_FIN = "청새치 파티 시작",
  PARTY_CUCUMBER = "오이 파티 시작",
  PARTY_LOBSTER = "랍스터 파티 시작",
  SECRET_RECIPE = "비밀 레시피",
}

export enum PARTY {
  TUNA = "참치 요트 파티",
  BLUE_FIN = "청새치 파티",
  CUCUMBER = "오이 파티",
  CURRY = "카레 파티",
}

export enum RECIPE_TYPE {
  FISH = "FISH",
  INGREDIENT = "INGREDIENT",
  SEASONING = "SEASONING",
}

export const DISH_LIST: Dish[] = [
  // 기본 초밥
  {
    id: "Clownfish_Sushi",
    name: "흰동가리 초밥",
    maxCost: 7,
    maxScore: 120,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰동가리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Comber_Sushi",
    name: "콤버 초밥",
    maxCost: 7,
    maxScore: 140,
    maxCount: 1,
    recipeList: [{ id: "", name: "콤버", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Cardinal Fish Sushi",
    name: "지중해카디널피쉬 초밥",
    maxCost: 11,
    maxScore: 100,
    maxCount: 1,
    recipeList: [
      { id: "", name: "지중해카디널피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sea Goldie Sushi",
    name: "금강바리",
    maxCost: 11,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "금강바리 초밥", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pyramid Butterflyfish Sushi",
    name: "안개나비고기 초밥",
    maxCost: 14,
    maxScore: 100,
    maxCount: 1,
    recipeList: [
      { id: "", name: "안개나비고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellow Tang Sushi",
    name: "옐로우탱 초밥",
    maxCost: 14,
    maxScore: 100,
    maxCount: 1,
    recipeList: [
      { id: "", name: "옐로우탱", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blackspot Seabream Sushi",
    name: "사르파살파 초밥",
    maxCost: 18,
    maxScore: 110,
    maxCount: 1,
    recipeList: [
      { id: "", name: "사르파살파", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Orbicular Batfish Fry",
    name: "원반제비활치 튀김",
    maxCost: 18,
    maxScore: 110,
    maxCount: 1,
    recipeList: [
      { id: "", name: "원반제비활치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blue Tang Sushi",
    name: "블루탱 초밥",
    maxCost: 22,
    maxScore: 110,
    maxCount: 1,
    recipeList: [{ id: "", name: "블루탱", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Rainbow Wrasse Sushi",
    name: "무지개놀래기 초밥",
    maxCost: 22,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무지개놀래기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Lagoon Triggerfish Sushi",
    name: "배주름쥐치 초밥",
    maxCost: 22,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "배주름쥐치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Small Spotted Dart Sushi",
    name: "빨판매가리 초밥",
    maxCost: 29,
    maxScore: 120,
    maxCount: 1,
    recipeList: [
      { id: "", name: "빨판매가리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowback Fusilier Sushi",
    name: "황등어 초밥",
    maxCost: 25,
    maxScore: 120,
    maxCount: 1,
    recipeList: [{ id: "", name: "황등어", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Ornate Wrasse Sushi",
    name: "오네이트놀래기 초밥",
    maxCost: 29,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "오네이트놀래기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Longfin Batfish Sushi",
    name: "깃털제비활치 초밥",
    maxCost: 37,
    maxScore: 130,
    maxCount: 1,
    recipeList: [
      { id: "", name: "깃털제비활치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Mediterranean Parrotfish Sushi",
    name: "지중해비늘돔 초밥",
    maxCost: 37,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "지중해비늘돔", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Redtooth Triggerfish Sushi",
    name: "붉은이빨쥐치 초밥",
    maxCost: 33,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "붉은이빨쥐치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Black and White Snapper Sushi",
    name: "블랙스내퍼 초밥",
    maxCost: 33,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블랙스내퍼", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Green Humphead Parrotfish Sushi",
    name: "버팔로피쉬 초밥",
    maxCost: 59,
    maxScore: 230,
    maxCount: 1,
    recipeList: [
      { id: "", name: "버팔로피쉬 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Barrel Jellyfish Sushi",
    name: "배럴해파리 군함 초밥",
    maxCost: 37,
    maxScore: 160,
    maxCount: 1,
    recipeList: [
      { id: "", name: "배럴해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Fried Egg Jellyfish Sushi",
    name: "달걀프라이해파리 군함 초밥",
    maxCost: 29,
    maxScore: 160,
    maxCount: 1,
    recipeList: [
      { id: "", name: "달걀프라이해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Whitetip Reefshark Sushi",
    name: "백기흉상어 초밥",
    maxCost: 88,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "백기흉상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Moray Eel Sushi",
    name: "곰치 초밥",
    maxCost: 185,
    maxScore: 250,
    maxCount: 1,
    recipeList: [{ id: "", name: "곰치", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Red Lionfish Sushi",
    name: "쏠배감펭 초밥",
    maxCost: 37,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "쏠배감펭", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Titan Triggerfish Sushi",
    name: "타이탄트리거피쉬 초밥",
    maxCost: 55,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "타이탄트리거피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blacktip Reefshark Sushi",
    name: "흑기흉상어 초밥",
    maxCost: 222,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흑기흉상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Copper Shark Sushi",
    name: "무태상어 초밥",
    maxCost: 240,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무태상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Box Jellyfish Sushi",
    name: "상자해파리 군함 초밥",
    maxCost: 203,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "상자해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluefin Tuna Akami Sushi",
    name: "참다랑어 붉은살 초밥",
    maxCost: 296,
    maxScore: 240,
    maxCount: 1,
    recipeList: [
      { id: "", name: "참다랑어 붉은살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluefin Tuna Chutoro Sushi",
    name: "참다랑어 중뱃살 초밥",
    maxCost: 351,
    maxScore: 241,
    maxCount: 1,
    recipeList: [
      { id: "", name: "참다랑어 중뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluefin Tuna Otoro Sushi",
    name: "참다랑어 대뱃살 초밥",
    maxCost: 499,
    maxScore: 330,
    maxCount: 1,
    recipeList: [
      { id: "", name: "참다랑어 대뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowfin Tuna Akami Sushi",
    name: "황다랑어 붉은살 초밥",
    maxCost: 270,
    maxScore: 235,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황다랑어 붉은살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowfin Tuna Chutoro Sushi",
    name: "황다랑어 중뱃살 초밥",
    maxCost: 333,
    maxScore: 238,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황다랑어 중뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Yellowfin Tuna Otoro Sushi",
    name: "황다랑어 대뱃살 초밥",
    maxCost: 462,
    maxScore: 315,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황다랑어 대뱃살", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Flame Angelfish Sushi",
    name: "라마엔젤피쉬 초밥",
    maxCost: 18,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "라마엔젤피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sheepshead Sushi",
    name: "혹돔 초밥",
    maxCost: 55,
    maxScore: 240,
    maxCount: 1,
    recipeList: [{ id: "", name: "혹돔", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Emperor Angelfish Sushi",
    name: "황제엔젤피쉬 초밥",
    maxCost: 37,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "황제엔젤피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Stingray Sushi",
    name: "노랑가오리 초밥",
    maxCost: 92,
    maxScore: 260,
    maxCount: 1,
    recipeList: [
      { id: "", name: "노랑가오리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Marbled Electric Ray Sushi",
    name: "마블전기가오리 초밥",
    maxCost: 333,
    maxScore: 300,
    maxCount: 1,
    recipeList: [
      { id: "", name: "마블전기가오리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Cooked Whiteleg Shrimp Sushi",
    name: "흰다리자숙새우 초밥",
    maxCost: 129,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰다리자숙새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Striped Catfish Sushi",
    name: "쏠종개 초밥",
    maxCost: 18,
    maxScore: 260,
    maxCount: 1,
    recipeList: [{ id: "", name: "쏠종개", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Purple Sea Urchin Sushi",
    name: "보라성게 초밥",
    maxCost: 222,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "보라성게 초밥", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Shortfin Mako Sushi",
    name: "청상아리 초밥",
    maxCost: 388,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "청상아리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Zebra Shark Sushi",
    name: "지브라상어 초밥",
    maxCost: 399,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "지브라상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Marlin Sushi",
    name: "청새치 초밥",
    maxCost: 341,
    maxScore: 370,
    maxCount: 1,
    recipeList: [
      { id: "", name: "청새치 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Thresher Shark Sushi",
    name: "환도상어 초밥",
    maxCost: 588,
    maxScore: 390,
    maxCount: 1,
    recipeList: [
      { id: "", name: "환도상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluehead Tilefish Sushi",
    name: "블루헤드타일피쉬 초밥",
    maxCost: 55,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블루헤드타일피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Clown Frogfish Sushi",
    name: "무당씬벵이 초밥",
    maxCost: 55,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무당씬벵이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Painted Comber Sushi",
    name: "페인티드콤버 초밥",
    maxCost: 32,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "페인티드콤버", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bigeye Scad Sushi",
    name: "새가라지 초밥",
    maxCost: 62,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "새가라지", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Striped Red Mullet Sushi",
    name: "노랑촉수 초밥",
    maxCost: 59,
    maxScore: 140,
    maxCount: 1,
    recipeList: [
      { id: "", name: "노랑촉수", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Mackerel Scad Sushi",
    name: "풀가라지 초밥",
    maxCost: 55,
    maxScore: 150,
    maxCount: 1,
    recipeList: [
      { id: "", name: "풀가라지", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Harleqiun Hind Sushi",
    name: "청줄바리 초밥",
    maxCost: 66,
    maxScore: 180,
    maxCount: 1,
    recipeList: [
      { id: "", name: "청줄바리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bigeye Trevally Sushi",
    name: "줄전갱이 초밥",
    maxCost: 70,
    maxScore: 170,
    maxCount: 1,
    recipeList: [
      { id: "", name: "줄전갱이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Coral Trout Sushi",
    name: "무늬바리 초밥",
    maxCost: 66,
    maxScore: 170,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무늬바리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Grey Triggerfish Sushi",
    name: "갈쥐치 초밥",
    maxCost: 62,
    maxScore: 170,
    maxCount: 1,
    recipeList: [{ id: "", name: "갈쥐치", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Atlantic Bonito Sushi",
    name: "대서양보니토 초밥",
    maxCost: 77,
    maxScore: 180,
    maxCount: 1,
    recipeList: [
      { id: "", name: "대서양보니토", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "White Trevally Sushi",
    name: "흑점줄전갱이 초밥",
    maxCost: 81,
    maxScore: 190,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흑점줄전갱이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Cuttlefish Sushi",
    name: "갑오징어 초밥",
    maxCost: 74,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "갑오징어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Dusky Grouper Sushi",
    name: "머구리농어 초밥",
    maxCost: 81,
    maxScore: 200,
    maxCount: 1,
    recipeList: [
      { id: "", name: "머구리농어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Atlantic Mackerel Sushi",
    name: "대서양고등어 초밥",
    maxCost: 77,
    maxScore: 190,
    maxCount: 1,
    recipeList: [
      { id: "", name: "대서양고등어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Giant Trevally Sushi",
    name: "무명갈전갱이 초밥",
    maxCost: 111,
    maxScore: 250,
    maxCount: 1,
    recipeList: [
      { id: "", name: "무명갈전갱이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Giant Trevally Sushi",
    name: "흰점박이해파리 군함 초밥",
    maxCost: 66,
    maxScore: 180,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰점박이해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Tiger Shark Sushi",
    name: "뱀상어 초밥",
    maxCost: 185,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "뱀상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Great Barracuda Sushi",
    name: "큰꼬치고기 초밥",
    maxCost: 74,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "큰꼬치고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Narrow_Barred Spanish Mackerel Sushi",
    name: "동갈삼치 초밥",
    maxCost: 74,
    maxScore: 190,
    maxCount: 1,
    recipeList: [
      { id: "", name: "동갈삼치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Longnose Sawshark Sushi",
    name: "톱상어 초밥",
    maxCost: 129,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "톱상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Atlantic Anglerfish Sushi",
    name: "대서양아귀 초밥",
    maxCost: 76,
    maxScore: 240,
    maxCount: 1,
    recipeList: [
      { id: "", name: "대서양아귀", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sally Lightfoot Crab Sushi",
    name: "갈라파고스붉은게살 초밥",
    maxCost: 185,
    maxScore: 320,
    maxCount: 1,
    recipeList: [
      { id: "", name: "갈라파고스붉은게", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Raw Black Tiger Shrimp Sushi",
    name: "블랙타이거생새우 초밥",
    maxCost: 185,
    maxScore: 240,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블랙타이거새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sailfish Sushi",
    name: "돛새치 초밥",
    maxCost: 336,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "돛새치 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Smooth Hammerhead Sushi",
    name: "귀상어 초밥",
    maxCost: 521,
    maxScore: 390,
    maxCount: 1,
    recipeList: [
      { id: "", name: "귀상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "White Shrimp Sushi",
    name: "흰보리새우 초밥",
    maxCost: 196,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흰보리새우", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Humboldt Squid Sushi",
    name: "훔볼트오징어 초밥",
    maxCost: 536,
    maxScore: 350,
    maxCount: 1,
    recipeList: [
      { id: "", name: "훔볼트오징어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Devil Scorpion Fish Sushi",
    name: "데빌스콜피온피쉬 초밥",
    maxCost: 499,
    maxScore: 350,
    maxCount: 1,
    recipeList: [
      { id: "", name: "데빌스콜피온피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Chambered Nautilus Sushi",
    name: "앵무조개 초밥",
    maxCost: 129,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "앵무조개", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Fangtooth Sushi",
    name: "귀신고기 초밥",
    maxCost: 166,
    maxScore: 260,
    maxCount: 1,
    recipeList: [
      { id: "", name: "귀신고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Frilled Shark Sushi",
    name: "주름상어 초밥",
    maxCost: 314,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "주름상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Bluespotted Stargazer Sushi",
    name: "푸렁통구멍 초밥",
    maxCost: 199,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "푸렁통구멍", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Rhinochimaeridae Sushi",
    name: "코은상어 초밥",
    maxCost: 333,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "코은상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Spider Crab Sushi",
    name: "키다리게 초밥",
    maxCost: 185,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "키다리게", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Megamouth Shark Sushi",
    name: "메가마우스상어 초밥",
    maxCost: 351,
    maxScore: 300,
    maxCount: 1,
    recipeList: [
      { id: "", name: "메가마우스상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Cookiecutter Shark Sushi",
    name: "쿠키커터상어 초밥",
    maxCost: 277,
    maxScore: 270,
    maxCount: 1,
    recipeList: [
      { id: "", name: "쿠키커터상어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Clione Sushi",
    name: "클리오네 초밥",
    maxCost: 129,
    maxScore: 220,
    maxCount: 1,
    recipeList: [
      { id: "", name: "클리오네", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Sea Toad Sushi",
    name: "점씬벵이 초밥",
    maxCost: 203,
    maxScore: 230,
    maxCount: 1,
    recipeList: [
      { id: "", name: "점씬벵이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Salmon Snailfish Sushi",
    name: "분홍꼼치 초밥",
    maxCost: 222,
    maxScore: 230,
    maxCount: 1,
    recipeList: [
      { id: "", name: "분홍꼼치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pacific Fanfish Sushi",
    name: "벤텐어 초밥",
    maxCost: 240,
    maxScore: 240,
    maxCount: 1,
    recipeList: [{ id: "", name: "벤텐어", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Threetooth Puffer Sushi",
    name: "불뚝복 초밥",
    maxCost: 259,
    maxScore: 250,
    maxCount: 1,
    recipeList: [{ id: "", name: "불뚝복", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Comb Jelly Sushi",
    name: "감투빗해파리 초밥",
    maxCost: 166,
    maxScore: 250,
    maxCount: 1,
    recipeList: [
      { id: "", name: "감투빗해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blood-belly Comb Jelly Sushi",
    name: "붉은배빗해파리 초밥",
    maxCost: 185,
    maxScore: 250,
    maxCount: 1,
    recipeList: [
      { id: "", name: "붉은배빗해파리", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Red Bream Sushi",
    name: "금눈돔 초밥",
    maxCost: 129,
    maxScore: 270,
    maxCount: 1,
    recipeList: [{ id: "", name: "금눈돔", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Peacock Squid Sushi",
    name: "공작오징어 초밥",
    maxCost: 277,
    maxScore: 290,
    maxCount: 1,
    recipeList: [
      { id: "", name: "공작오징어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Dumbo Octopus Sushi",
    name: "덤보문어 초밥",
    maxCost: 296,
    maxScore: 330,
    maxCount: 1,
    recipeList: [
      { id: "", name: "덤보문어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Barreleye Sushi",
    name: "배럴아이 초밥",
    maxCost: 259,
    maxScore: 280,
    maxCount: 1,
    recipeList: [
      { id: "", name: "배럴아이", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Blob Fish Sushi",
    name: "블롭피쉬 초밥",
    maxCost: 444,
    maxScore: 310,
    maxCount: 1,
    recipeList: [
      { id: "", name: "블롭피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Vampire Squid Sushi",
    name: "흡혈오징어",
    maxCost: 425,
    maxScore: 340,
    maxCount: 1,
    recipeList: [
      { id: "", name: "흡혈오징어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pelican Eel Sushi",
    name: "펠리칸장어 초밥",
    maxCost: 666,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "펠리칸장어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Arctic Cod Sushi",
    name: "극지대구 초밥",
    maxCost: 351,
    maxScore: 340,
    maxCount: 1,
    recipeList: [
      { id: "", name: "극지대구", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Gelatinous Snailfish Sushi",
    name: "남극꼼치 초밥",
    maxCost: 314,
    maxScore: 330,
    maxCount: 1,
    recipeList: [
      { id: "", name: "남극꼼치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Antarctic Octopus Sushi",
    name: "남극문어 초밥",
    maxCost: 444,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "남극문어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Greenland Shark Sushi",
    name: "그린란드상어 초밥",
    maxCost: 592,
    maxScore: 370,
    maxCount: 1,
    recipeList: [
      { id: "", name: "그린란드상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Polar Eelpout Sushi",
    name: "북극등가시치 초밥",
    maxCost: 333,
    maxScore: 320,
    maxCount: 1,
    recipeList: [
      { id: "", name: "북극등가시치", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Porbeagle Shark Sushi",
    name: "비악상어 초밥",
    maxCost: 610,
    maxScore: 380,
    maxCount: 1,
    recipeList: [
      { id: "", name: "비악상어 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Ice Fish Sushi",
    name: "아이스피쉬 초밥",
    maxCost: 351,
    maxScore: 320,
    maxCount: 1,
    recipeList: [
      { id: "", name: "아이스피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Capelin Sushi",
    name: "열빙어 초밥",
    maxCost: 166,
    maxScore: 330,
    maxCount: 1,
    recipeList: [{ id: "", name: "열빙어", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Narwhal Sushi",
    name: "일각고래 초밥",
    maxCost: 518,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "일각고래 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Haddock Sushi",
    name: "해덕대구 초밥",
    maxCost: 407,
    maxScore: 340,
    maxCount: 1,
    recipeList: [
      { id: "", name: "해덕대구", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Starry Skate Sushi",
    name: "땅가오리 초밥",
    maxCost: 481,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "땅가오리 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Arctic Telescope Fish Sushi",
    name: "북극 망원경 물고기 초밥",
    maxCost: 444,
    maxScore: 350,
    maxCount: 1,
    recipeList: [
      { id: "", name: "북극 망원경 물고기", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Alaska Pollock Sushi",
    name: "알래스카 명태 초밥",
    maxCost: 499,
    maxScore: 380,
    maxCount: 1,
    recipeList: [
      { id: "", name: "알래스카 명태", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Lumpfish Sushi",
    name: "럼프피쉬 초밥",
    maxCost: 444,
    maxScore: 370,
    maxCount: 1,
    recipeList: [
      { id: "", name: "럼프피쉬", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Snub_nosed Spiny Eel Sushi",
    name: "들창코가시장어 초밥",
    maxCost: 666,
    maxScore: 390,
    maxCount: 1,
    recipeList: [
      { id: "", name: "들창코가시장어", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Waptia Sushi",
    name: "왑티아 초밥",
    maxCost: 381,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "왑티아 필덴시스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Pikaia Sushi",
    name: "피카이아 초밥",
    maxCost: 425,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "피카이아", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Allenypterus Sushi",
    name: "알레니프테루스 초밥",
    maxCost: 462,
    maxScore: 360,
    maxCount: 1,
    recipeList: [
      { id: "", name: "알레니프테루스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Qingmendous Sushi",
    name: "칭멘도스 초밥",
    maxCost: 444,
    maxScore: 310,
    maxCount: 1,
    recipeList: [
      { id: "", name: "칭멘도스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Falcatus Sushi",
    name: "팔카투스 초밥",
    maxCost: 481,
    maxScore: 380,
    maxCount: 1,
    recipeList: [
      { id: "", name: "팔카투스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Drepanaspis Sushi",
    name: "드레파나스피스 초밥",
    maxCost: 555,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "드레파나스피스 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Dunkleosteus Sushi",
    name: "둔클레오스테우스 초밥",
    maxCost: 629,
    maxScore: 420,
    maxCount: 1,
    recipeList: [
      {
        id: "",
        name: "둔클레오스테우스 살점",
        type: RECIPE_TYPE.FISH,
        count: 1,
      },
    ],
  },
  {
    id: "Megalograptus Sushi",
    name: "메갈로그랍투스 초밥",
    maxCost: 518,
    maxScore: 400,
    maxCount: 1,
    recipeList: [
      { id: "", name: "메갈로그랍투스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Xenacanthus Sushi",
    name: "제나칸투스 초밥",
    maxCost: 592,
    maxScore: 430,
    maxCount: 1,
    recipeList: [
      { id: "", name: "제나칸투스 살점", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Young Anomalocaris Sushi",
    name: "아노말로칼리스 새끼 초밥",
    maxCost: 224,
    maxScore: 125,
    maxCount: 1,
    recipeList: [
      { id: "", name: "아노말로칼리스", type: RECIPE_TYPE.FISH, count: 1 },
    ],
  },
  {
    id: "Seahorse Sewers",
    name: "해마 꼬치구이",
    maxCost: 111,
    maxScore: 220,
    maxCount: 1,
    recipeList: [{ id: "", name: "해마", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "Seadragon Onigiri",
    name: "해룡 주먹밥",
    maxCost: 388,
    maxScore: 470,
    maxCount: 1,
    recipeList: [{ id: "", name: "해룡", type: RECIPE_TYPE.FISH, count: 1 }],
  },
  {
    id: "",
    name: "",
    unlockType: UNLOCK_TYPE.YOSHIE_VISIT,
    maxCost: 0,
    maxScore: 0,
    maxCount: 1,
    recipeList: [{ id: "", name: "", type: RECIPE_TYPE.FISH, count: 1 }],
  },
];
