import { Fish } from "@typings/Fish.ts";
import { REGION } from "@constants/Region.ts";
import { TIME } from "@constants/Time.ts";
import { RANK } from "@constants/Rank.ts";

export const FISH_LIST: Fish[] = [
  // 블루홀 초입
  {
    id: "Clownfish",
    name: "흰동가리",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Comber",
    name: "콤버",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Cardinal_Fish",
    name: "지중해카디널피쉬",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Sea_Goldie",
    name: "금강바리",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Pyramid_Butterflyfish",
    name: "안개나비고기",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Yellow_Tang",
    name: "옐로우탱",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Salema_Porgy",
    name: "사르파살파",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Orbicular_Batfish",
    name: "원반제비활치",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Blue_Tang",
    name: "블루탱",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Rainbow_Wrasse",
    name: "무지개놀래기",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Lagoon_Triggerfish",
    name: "배주름쥐치",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Small_Spotted_Dart",
    name: "빨판매가리",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Yellowback_Fusilier",
    name: "황등어",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Ornate_Wrasse",
    name: "오네이트놀래기",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Longfin_Batfish",
    name: "깃털제비활치",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Mediterranean_Parrotfish",
    name: "지중해비늘돔",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Redtooth_Triggerfish",
    name: "붉은이빨쥐치",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Black_And_White_Snapper",
    name: "블랙스내퍼",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Green_Humphead_Parrotfish",
    name: "버팔로피쉬",
    rank: RANK.THREE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Barrel_Jellyfish",
    name: "배럴해파리",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Fried_Egg_Jellyfish",
    name: "달걀프라이해파리",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Whitetip_Reefshark",
    name: "백기흉상어",
    rank: RANK.FOUR,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Starry_Puffer",
    name: "꺼끌복",
    rank: RANK.THREE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Red_Lionfish",
    name: "쏠배감펭",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Titan_Triggerfish",
    name: "타이탄트리거피쉬",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Bluefin_Tuna",
    name: "참다랑어",
    rank: RANK.SEVEN,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Yellowfin_Tuna",
    name: "황다랑어",
    rank: RANK.SEVEN,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Flame_Angelfish",
    name: "라마엔젤피쉬",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Sheepshead",
    name: "혹돔",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Emperor_Angelfish",
    name: "황제엔젤피쉬",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Stingray",
    name: "노랑가오리",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Marbled_Electric_Ray",
    name: "마블전기가오리",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Whiteleg_Shrimp",
    name: "흰다리새우",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Striped_Catfish",
    name: "쏠종개",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Purple_Sea_Urchin",
    name: "보라성게",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Shortfin_Mako",
    name: "청상아리",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Marlin",
    name: "청새치",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "Thresher_Shark",
    name: "환도상어",
    rank: RANK.NINE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "American_Lobster",
    name: "미국바닷가재",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  {
    id: "European_Lobster",
    name: "유렵바닷가재",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.DAY,
  },
  // 블루홀 중간 수역
  {
    id: "Bluehead_Tilefish",
    name: "블루헤드타일피쉬",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Clown_Frogfish",
    name: "무당씬벵이",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Painted_Comber",
    name: "페인티드콤버",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Bigeye_Scad",
    name: "새가라지",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Striped_Red_Mullet",
    name: "노랑촉수",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Mackerel_Scad",
    name: "풀가라지",
    rank: RANK.ONE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Harleqiun_Hind",
    name: "청줄바리",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Bigeye_Trevally",
    name: "줄전갱이",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Coral_Trout",
    name: "무늬바리",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Grey_Triggerfish",
    name: "갈쥐치",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Atlantic_Bonito",
    name: "대서양보니토",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "White_Trevally",
    name: "흑점줄전갱이",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Cuttlefish",
    name: "갑오징어",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Dusky_Grouper",
    name: "머구리농어",
    rank: RANK.THREE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Atlantic_Mackerel",
    name: "대서양고등어",
    rank: RANK.THREE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Giant_Trevally",
    name: "무명갈전갱이",
    rank: RANK.FOUR,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "White_Spotted_Jellyfish",
    name: "흰점박이해파리",
    rank: RANK.TWO,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Tiger_Shark",
    name: "뱀상어",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Great_Barracuda",
    name: "큰꼬치고기",
    rank: RANK.THREE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Narrow_Barred_Spanish_Mackerel",
    name: "동갈삼치",
    rank: RANK.THREE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Longnose_Sawshark",
    name: "톱상어",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Atlantic_Anglerfish",
    name: "대서양아귀",
    rank: RANK.FOUR,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Sally_Lightfoot_Crab",
    name: "갈라파고스붉은게",
    rank: RANK.SEVEN,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Black_Tiger_Shrimp",
    name: "블랙타이거새우",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Smooth_Hammerhead",
    name: "귀상어",
    rank: RANK.NINE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Sailfish",
    name: "돛새치",
    rank: RANK.NINE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "California_Spiny_Lobster",
    name: "캘리포니아닭새우",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Tropical_Rock_Lobster",
    name: "비단닭새우",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.DAY,
  },
  // 블루홀 심해
  {
    id: "Chambered_Nautilus",
    name: "앵무조개",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Fangtooth",
    name: "귀신고기",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Frilled_Shark",
    name: "주름상어",
    rank: RANK.SEVEN,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Bluespotted_Stargazer",
    name: "푸렁통구멍",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Rhinochimaeridae",
    name: "코은상어",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Spider_Crab",
    name: "키다리게",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Megamouth_Shark",
    name: "메가마우스상어",
    rank: RANK.SEVEN,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Cookiecutter_Shark",
    name: "쿠키커터상어",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Clione",
    name: "클리오네",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Sea_Toad",
    name: "점씬벵이",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Salmon_Snailfish",
    name: "분홍꼼치",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Pacific_Fanfish",
    name: "벤텐어",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Threethooth_Puffer",
    name: "불뚝복",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Comb_Jelly",
    name: "감투빗해파리",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Blood_Belly_Comb_Jellyfish",
    name: "붉은배빗해파리",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Red_Bream",
    name: "금눈돔",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Norway_Lobster",
    name: "네점발빨간새우",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  {
    id: "Eastern_Rock_Lobster",
    name: "동부바위바닷가재",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_DEPTH,
    time: TIME.DAY,
  },
  // 야행성
  {
    id: "Clearfin_Lionfish",
    name: "방사쏠배감펭",
    rank: RANK.FOUR,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Longspine_Squirrelfish",
    name: "롱스파인 다람쥐고기",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Longspine_Porcupinefish",
    name: "가시복",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Box_Jellyfish",
    name: "상자해파리",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Moray_Eel",
    name: "곰치",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Blacktip_Reefshark",
    name: "흑기흉상어",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Copper_Shark",
    name: "무태상어",
    rank: RANK.SIX,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Zebra_Shark",
    name: "지브라상어",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "White_Shrimp",
    name: "흰보리새우",
    rank: RANK.SEVEN,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Red_Banded_Lobster",
    name: "가시발새우",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Blue_Lobster",
    name: "블루랍스터",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_SHALLOWS,
    time: TIME.NIGHT,
  },
  {
    id: "Blackfin_Barracuda",
    name: "검정핀꼬치고기",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.NIGHT,
  },
  {
    id: "Spear_Squid",
    name: "화살오징어",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.NIGHT,
  },
  {
    id: "Humboldt_Squid",
    name: "훔볼트오징어",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.NIGHT,
  },
  {
    id: "Devil_Scorpion_Fish",
    name: "데빌스콜피온피쉬",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.NIGHT,
  },
  {
    id: "Fan_Lobster",
    name: "부채새우",
    rank: RANK.FIVE,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.NIGHT,
  },
  {
    id: "Crystal_Lobster",
    name: "크리스탈랍스터",
    rank: RANK.EIGHT,
    region: REGION.BLUE_HOLE_MEDIUM_DEPTH,
    time: TIME.NIGHT,
  },
  // 빙하 통로
  {
    id: "Peacock_Squid",
    name: "공작오징어",
    rank: RANK.SEVEN,
    region: REGION.GLACIER_PASSAGE,
    time: TIME.DAY,
  },
  {
    id: "Dumbo_Octopus",
    name: "덤보문어",
    rank: RANK.SEVEN,
    region: REGION.GLACIER_PASSAGE,
    time: TIME.DAY,
  },
  {
    id: "Barreleye",
    name: "배럴아이",
    rank: RANK.SEVEN,
    region: REGION.GLACIER_PASSAGE,
    time: TIME.DAY,
  },
  {
    id: "Blob_Fish",
    name: "블롭피쉬",
    rank: RANK.SEVEN,
    region: REGION.GLACIER_PASSAGE,
    time: TIME.DAY,
  },
  {
    id: "Vampire_Squid",
    name: "흡혈오징어",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_PASSAGE,
    time: TIME.DAY,
  },
  {
    id: "Pelican_Eel",
    name: "펠리칸장어",
    rank: RANK.NINE,
    region: REGION.GLACIER_PASSAGE,
    time: TIME.DAY,
  },
  // 빙하 지역
  {
    id: "Arctic_Cod",
    name: "극지대구",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Gelatinous_Snailfish",
    name: "남극꼼치",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Antarctic_Octopus",
    name: "남극문어",
    rank: RANK.NINE,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Greenland_Shark",
    name: "그린란드상어",
    rank: RANK.NINE,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Polar_Eelpout",
    name: "북극등가시치",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Porbeagle_Shark",
    name: "비악상어",
    rank: RANK.NINE,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Ice_Fish",
    name: "아이스피쉬",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Capelin",
    name: "열빙어",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Narwhal",
    name: "일각고래",
    rank: RANK.NINE,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Haddock",
    name: "해덕대구",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Starry_Skate",
    name: "땅가오리",
    rank: RANK.NINE,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Arctic_Telescope_Fish",
    name: "북극 망원경 물고기",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Alaska_Pollock",
    name: "알래스카 명태",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Lumpfish",
    name: "럼프피쉬",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Snub_Nosed_Spiny_Eel",
    name: "들창코가시장어",
    rank: RANK.NINE,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Golden_King_Crab",
    name: "황색왕게",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Snow_Crab",
    name: "대게",
    rank: RANK.EIGHT,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  {
    id: "Horsehair_Crab",
    name: "털게",
    rank: RANK.NINE,
    region: REGION.GLACIER_ZONE,
    time: TIME.DAY,
  },
  // 열수 분출구
  {
    id: "Waptia_Fieldensis",
    name: "왑티아 필덴시스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Pikaia",
    name: "피카이아",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Allenypterus",
    name: "알레니프테루스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Qingmendous",
    name: "칭멘도스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Falcatus",
    name: "팔카투스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Drepanaspis",
    name: "드레파나스피스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Dunkleosteus",
    name: "둔클레오스테우스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Megalograptus",
    name: "메갈로그랍투스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Xenacanthus",
    name: "제나칸투스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Dollocaris_Ingens",
    name: "돌로카리스인겐스",
    rank: RANK.EIGHT,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Tokummia_Katalepsis",
    name: "토큐미아카탈렙시스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  {
    id: "Anomalocaris",
    name: "아노말로칼리스",
    rank: RANK.NINE,
    region: REGION.HYDROTHERMAL_VENTS,
    time: TIME.DAY,
  },
  // 기타
  {
    id: "Seahorse",
    name: "해마",
    rank: RANK.FOUR,
    region: REGION.ETC,
    time: TIME.DAY,
  },
  {
    id: "Seadragon",
    name: "해룡",
    rank: RANK.EIGHT,
    region: REGION.ETC,
    time: TIME.DAY,
  },
];
